name = "tiny_tensors"
description = "A smal library for vectors, matrices and linear algebra"
version = "0.1.0-dev"

authors = ["Max Reznik"]
maintainers = ["Max Reznik <reznikmm@gmail.com>"]
maintainers-logins = ["reznikmm"]
licenses = "Apache-2.0 WITH LLVM-exception"
website = "https://github.com/reznikmm/tiny-tensors"
tags = ["eigen"]

project-files = ["gnat/tiny_tensors.gpr"]
